### ISSUE TITLE
`container` class issue

### ISSUE THREAD

**Issue by stebogit** [ResponsiveBP/Responsive#100]
Hello, I had an issue with the (quite common) `container` class of the Modal module, which collides with the same class name from another library.
I'd suggest to rename the class to something more "contained", like `modal-container` for instance.
I did that (on both `css` and `js` files) and it seems to work.

**Comment by JimBobSquarePants** [comment]
Hi there, 

I'm not going to be remaining any classes any time soon. What library is it?

**Comment by stebogit** [comment]
@JimBobSquarePants thanks for answering.
It's actually a web template I used, where the `container` class is used for wrapping the page content. I just see it as a quite common word for a class name in a web page.
However, I renamed my template classes.
