### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by appernetic** [ResponsiveBP/Responsive#101]
I am having a hard time following the instructions. It would be very helpful with one or two plunkers to see how it all works.

**Comment by JimBobSquarePants** [comment]
One or two plunkers? 

The entire website is brimming with comprehensive documentation and live examples. What exactly are you struggling with?

**Comment by JimBobSquarePants** [comment]
For example I've covered pretty much every scenario for the modal plugin here plus api docs. 

http://responsivebp.com/javascript/modal/

**Comment by appernetic** [comment]
Just to get started is easy with a plnkr, you get to see both the html and javscript code in it's context. I am a bit lazy and plnkr's is perfect to experiment with. I will do a couple of plnker when I have learnt it and share them.

**Comment by JimBobSquarePants** [comment]
Ah... You mean this? http://plnkr.co/

I'd never heard of it until now. 

Any questions please ask, I've also got a Gitter channel which is always good for a chat.

https://gitter.im/ResponsiveBP/Responsive

**Comment by appernetic** [comment]
Yes, thats right.

Probably it't to easy. But I am struggling to find the js code and the code for the modal. I am used to build complex Angular apps..

Ok, Great, I use gitter a lot.

**Comment by JimBobSquarePants** [comment]
Most of the time you just want to use the data-attribute API, everything wires up automatically. The code is good old fashioned jQuery plugin format though.

**Comment by appernetic** [comment]
I have a problem with the css. I can't include all the classes from responsive.css, then the rest of the site will look like shit. I tried with only the modal classes, but this is not enough.

**Comment by JimBobSquarePants** [comment]
It's supposed to be used as a base, that is then built upon, opting into components. Doing the reverse won't work.

**Comment by appernetic** [comment]
Ok, trying to implement it in a WordPress site..

**Comment by appernetic** [comment]
Maybe I have to use a simple plugin instead...

It worked fine in my test index file. Great work!

I am closing this issue now!

**Comment by JimBobSquarePants** [comment]
No worries, yeah choose the best tool for the job. Maybe next time 😄
