### ISSUE TITLE
Can not close modal?

### ISSUE THREAD

**Issue by tuan072090** [ResponsiveBP/Responsive#103]
Hello,

I use this code to create a modal with content 
`$('<a/>').modal({
                target: "#overlayDishSpec",
                fitViewport: true,
                immediate: true});`
It work fine, but how can I close it by calling javascript or jquery function?

And one more thing is how can I customize modal size? "EX: width: 50%"

**Comment by JimBobSquarePants** [comment]
Hi @tuan072090 

If you call the target again passing the method `hide` you will be able to close the model

e.g.
``` js
// Init
var $trigger = $("<a/>");
$trigger.modal({ target: "#overlayDishSpec", fitViewport: true, immediate: true});

// Later on...
$trigger.modal("hide");
```
http://responsivebp.com/javascript/modal/#methods

To change the width you have to use CSS.

``` css
.modal-ajax.container, .modal-iframe {
    max-width: 50%;
}
```
Hope that all makes sense.

Cheers

James

**Comment by tuan072090** [comment]
Thank @JimBobSquarePants , It's working now.
