### ISSUE TITLE
Loosen jquery dependency in npm package

### ISSUE THREAD

**Issue by michaelchart** [ResponsiveBP/Responsive#105]
Currently, the [jquery dependency in the package.json](https://github.com/ResponsiveBP/Responsive/blob/v4/package.json#L51) is strictly set to the specific jquery version 2.1.4. Presumably, ResponsiveBP would acually work with newer versions of jquery, and this dependency could be loosened to be ">=2.1.4"?

We are using other npm packages that have dependencies on newer versions of jquery, so resolving these different dependencies is becoming difficult.

**Comment by JimBobSquarePants** [comment]
Yeah definitely. I didn't realise it was so explicit. Can you make a PR?

**Comment by JimBobSquarePants** [comment]
Just pushed 4.1.4 to NPM with your update. Thanks!
