### ISSUE TITLE
How can I disable Responsive Tabs?

### ISSUE THREAD

**Issue by blueyestar** [ResponsiveBP/Responsive#111]
How can I disable Responsive tabs because it is conflict with jQuery UI.

I want to use jQuer UI's Tabs plugin, not Responsive's tabs.

Thanks

**Comment by JimBobSquarePants** [comment]
It in the docs

https://responsivebp.com/javascript/tabs/#dataapi

``` javascript
// Disable the default loading behaviour
$(document).off(".r.tabs.data-api");
```
