### ISSUE TITLE
Help on lightbox

### ISSUE THREAD

**Issue by anandbohra** [ResponsiveBP/Responsive#112]
pl let me know how to open lightbox on page load.

<div id="MyLightBox" class="hidden" >
    <p>
       This is My Light Box.
    </p>
</div>

$(document).ready(function () {
$("#MyLightbox").lightbox("Show");
});

it just shows grey screen but model doesnot appear

**Comment by JimBobSquarePants** [comment]
Hi @anandbohra 

Apologies for the slow reply. It's been a while since I looked at the library.

There is no `lightbox` method in the library. I'm not sure you're in the right place?

The model plugin documentation is here.

https://responsivebp.com/javascript/modal/
