### ISSUE TITLE
[Question]  Breakpoints

### ISSUE THREAD

**Issue by DanielHitchen** [ResponsiveBP/Responsive#48]
Hi, Love this framework by the way, great alternative to TwitterBS & Foundation, without the bloat :)

Just one question, the minimum breakpoint for the grid is set to ```Up to 48em (768px at 16px/1em)``` using ```col-xs-XX``` for example, is there any chance we could get 1 or 2 more BPs before this for smaller devices?

For example, for devices smaller than ```768px``` in width i.e smaller tablets or landscape smartphones (iPhone5 for example), I may want to keep a 2 column layout and only go to a single column layout when the device width is ```320px```, whereas at the moment, it's a single column layout for ALL devices up to ```768px```.

Maybe set another BP at ```Up to 37.5em (600px at 16px/1em)``` to catch landscape iPhones & vertical small tablets, and again at ```Up to 30em (480px at 16px/1em)``` to catch all mobile devices – maybe using classes of ```col-xxs-XX``` and ```col-mob-XX```?

I hope that all makes sense. Just feel that having a few extra options below ```768px``` would be helpful :)

PS. If i've missed something in the docs that achieves the above, I apologise in advance.

**Comment by JimBobSquarePants** [comment]
Fixed with v4. We now have an extra breakpoint at 37.5em. http://responsivebp.com/css/grid/#mediaqueries
