### ISSUE TITLE
Bug when expanding collapsible widgets on iOS Safari

### ISSUE THREAD

**Issue by cvrebert** [ResponsiveBP/Responsive#54]
1. Open http://responsivebp.com in Safari on iPhone
2. Tap the hamburger icon
3. The navbar expands, collapses, and then expands again. It should instead expand only once and remain expanded until interacted with further.

**Comment by JimBobSquarePants** [comment]
Thanks, seems like something is causing a repaint on Safari before it should. 

Do the samples for the dropdown and accordion do the same?

http://responsivebp.com/javascript/dropdown/

**Comment by cvrebert** [comment]
Yes, the dropdown and the accordion suffer from the same bug.

**Comment by JimBobSquarePants** [comment]
Thanks. Just confirmed it on Safari on desktop also. Gotta love these Safari bugs eh?

**Comment by JimBobSquarePants** [comment]
I wouldn't normally do a release as quickly as this but I think it was such a fundamental issue that it was best to.
