### ISSUE TITLE
Docs typos

### ISSUE THREAD

**Issue by cvrebert** [ResponsiveBP/Responsive#55]
Just as it's not "Surfbort" but "Surfboard", it's not "Keybord" but "Keyboard".
The typo "Keybord" present in several places in the docs site.

**Comment by cvrebert** [comment]
Additional typos found:
* "accesibility"
* "detaction"
* "vviewport"
* "visibilty"

**Comment by JimBobSquarePants** [comment]
Thanks. Note to self, install a spell-checker.
