### ISSUE TITLE
Modal option docs not clear on plaintext vs. HTML

### ISSUE THREAD

**Issue by cvrebert** [ResponsiveBP/Responsive#59]
e.g. The `title` option is described as "text" but is in fact used as raw HTML. Same thing goes for some of the other options.
Similarly, the `closeHint` option (among others) is vaguely described as "A hidden value" but again is used as raw HTML.

This can lead to unintended HTML injection!

I have not checked whether the docs for other plugins have similar issues.

**Comment by JimBobSquarePants** [comment]
Updated to specify type as html
