### ISSUE TITLE
Modal stacking?

### ISSUE THREAD

**Issue by cvrebert** [ResponsiveBP/Responsive#65]
Is it possible to open one modal while another is already open, such that closing the 2nd modal will bring the 1st modal back to the foreground, without having to explicitly have the 2nd modal reference the 1st modal (e.g. the 2nd modal might be summoned from multiple different places) ?

**Comment by JimBobSquarePants** [comment]
I'm afraid not at the moment, It's an interesting idea though. 

I guess it could be possible though without breaking the overall API though. I could store an array of instances that are not explicitly closed and retrieve them on closure of any following instance. Something to investigate anyway.

**Comment by JimBobSquarePants** [comment]
Closing as I don't think I'll ever implement this. Not a fan of modals anyway.
