### ISSUE TITLE
Grouped Accordion

### ISSUE THREAD

**Issue by Hardik-Savani** [ResponsiveBP/Responsive#68]
Hi,

How can I add plus and minus symbol / sign to accordion so when it open, shows minus sign and close plus sign.

And also, I would like to know if i can make fix position for close X sign in Launch overlay. I tried to set the position but the content's height is not fixed so every time it changes the position.

Thanks,
h

**Comment by JimBobSquarePants** [comment]
Hi there,

Sorry for the slow reply. I'll knock up an example accordion for you as soon as I can.

I'm not sure I follow what you are trying to achieve with the  second question. Do you mean the [modal](http://responsivebp.com/javascript/modal/) plugin? Could you post an image of what you are looking for?

**Comment by craigs100** [comment]
Could be talking about the X to close the Modal window being at the top right of the screen rather than the top right of the content (like Fancybox etc.). Similar issue with the title too. Position relative to window rather than content.

**Comment by JimBobSquarePants** [comment]
Ah maybe...

The layout was done the way it was for good reason, a constantly changing location is bad for usability and the behaviour I chose matches others like Magnificent Popup and Google's internal lightbox designs. 

I doubt I'll ever be changing it.

**Comment by JimBobSquarePants** [comment]
CSS would be the best approach here I think. Use the following selectors.

```
/*
 * Expanded
 */
.accordion-head [aria-expanded="true"] {
}

/*
 * Collapsed
 */
.accordion-head [aria-expanded="false"] {
}
```
