### ISSUE TITLE
Modal title when loading manually

### ISSUE THREAD

**Issue by jsantari** [ResponsiveBP/Responsive#71]
When loading manually how can I get the modal title to be taken from the link? It doesn't pick up the attribute data-modal-title if I provide it. In my case since the modal is showing photo's for a single property I'd like to display the MLS number and price for example in the title when the modal opens.

**Comment by JimBobSquarePants** [comment]
Since you're not using the Data Api  the plugin will not automatically load properties. You need to assign a property in you options.

```
var options = {
    title : YourTitle,
    // Other options...
}
```

**Comment by jsantari** [comment]
Except that means then that I can't set the title for each modal that I 
show for each listing. I only get to set one title to display for all 
property listings which is not what I was hoping for. If I was attaching 
an event handler with jquery in the event I could do something like 
this. $(this).attr('data-modal-title') and use it however I wanted. I 
was hoping I could pick the title like that in the modal by specifying 
it in the options - for example by setting title: 'data-modal-title' or 
some such option.

On 4/11/2015 4:45 AM, James South wrote:
>
> Since you're not using the Data Api the plugin will not automatically 
> load properties. You need to assign a property in you options.
>
> |var options = {
>      title : YourTitle,
>      // Other options...
> }
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ResponsiveBP/Responsive/issues/71#issuecomment-91805289>.
>

-- 
Jim Santarius
NCC Technology Group

**Comment by JimBobSquarePants** [comment]
You're getting confused with the scope of the "this" keyword within JavaScript. In an event the code within the bound function is scoped to the target of the event. That means that "this" means your object. 

When initialising your plugin "this" is scoped to the containing function not the object itself. 

For example...
**Event**
```
$("target").click(function(event){
    // The object 'this' inside this function refers to the  item that the event is bound to.
});
```

**Plugin**
```
$("target").modal({
    // The code here cannot possibly work. 
    // The keyword 'this' is scoped to the function in which this code is contained.
    target :  $(this).attr("data-modal-title") 
});
```

What you need to do is bind to objects with scope pointing to that object within a collection. 

```
$("target").each(function(){
    // 'this' is now scoped to the object within the collection.  
    var $this = $(this);
    $this.modal({
        target :  $this.attr("data-modal-title") 
        // Other settings...
    });
});
```

**Comment by jsantari** [comment]
Ok - sort of understand. But, how is it then that it is able to get the 
href value but not the data-modal-title?

On 4/11/2015 10:27 AM, James South wrote:
>
> You're getting confused with the scope of the "this" keyword within 
> JavaScript. In an event the code within the bound function is scoped 
> to the target of the event. That means that "this" means your object.
>
> When initialising your plugin "this" is scoped to the containing 
> function not the object itself.
>
> For example...
> *Event*
>
> |$("target").click(function(event){
>      // The object 'this' inside this function refers to the  item that the event is bound to.
> });
> |
>
> *Plugin*
>
> |$("target").modal({
>      // The code here cannot possibly work.
>      // The keyword 'this' is scoped to the function in which this code is contained.
>      target :  $(this).attr("data-modal-title")
> });
> |
>
> What you need to do is bind to objects with scope pointing to that 
> object within a collection.
>
> |$("target").each(function(){
>      // 'this' is now scoped to the object within the collection.
>      var $this = $(this);
>      $this.modal({
>          target :  $this.attr("data-modal-title")
>          // Other settings...
>      });
> });
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ResponsiveBP/Responsive/issues/71#issuecomment-91869498>.
>

-- 
Jim Santarius
NCC Technology Group

**Comment by JimBobSquarePants** [comment]
You can't. Not in that way anyway. We already established that here. https://github.com/ResponsiveBP/Responsive/issues/70#issuecomment-88651582

The value from the href is populated because internally within the plugin I check for a fallback href property on the element as the target. 

https://github.com/ResponsiveBP/Responsive/blob/master/src/js/responsive.modal.js#L721 

I can't possible detect other properties since I do not know where they will come from. That's why the data-api exists.

**Comment by jsantari** [comment]
Ok - I was able to implement the title the way I wanted based on your 
example using a click event like this.

   $('a.modal-pics').on('click', function(e) {
     e.preventDefault();
     var $this = $(this);
       $this.modal(
         {
           fitViewport: false,
           iframeScroll: false,
           immediate: true,
           title: $this.attr('data-modal-title')
         }
       );
   });

Works great - thanks for all the help.

On 4/11/2015 11:32 AM, James South wrote:
>
> You can't. Not in that way anyway. We already established that here. 
> #70 (comment) 
> <https://github.com/ResponsiveBP/Responsive/issues/70#issuecomment-88651582>
>
> The value from the href is populated because internally within the 
> plugin I check for a fallback href property on the element as the target.
>
> https://github.com/ResponsiveBP/Responsive/blob/master/src/js/responsive.modal.js#L721 
>
>
> I can't possible detect other properties since I do not know where 
> they will come from. That's why the data-api exists.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ResponsiveBP/Responsive/issues/71#issuecomment-91876839>.
>

-- 
Jim Santarius
NCC Technology Group

**Comment by JimBobSquarePants** [comment]
I wouldn't bind to click since the modal binds a click event to the element anyway and you will end up double binding. You are much better doing as I said and using `$.each` from within your ajax load event handler.
