### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jonespen** [ResponsiveBP/Responsive#72]
https://www.npmjs.com/package/responsive doesn't exist (or is my search fu bad?)

Would make it easier to use with [webpack](http://webpack.github.io/) / [sass-loader](https://github.com/jtangelder/sass-loader)

Great project btw :)

**Comment by JimBobSquarePants** [comment]
Thanks!... Much more goodies to come very soon. :smile: 

To be honest that's the very first time I've even seen that site. I've set up an [account](https://www.npmjs.com/~responsivebp) but I don't know if there are any code changes required on my part before I submit any packages. 

Do you have any pointers?

**Comment by jonespen** [comment]
I have no idea tbh, never published a npm package before heh

But it shouldn't be that hard, have you tried `npm publish`? Maybe you need to add a [main](https://docs.npmjs.com/files/package.json#main) field to `package.json` ([bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/master/package.json) could be a good source for inspiration)

**Comment by JimBobSquarePants** [comment]
I'll see what I can do... I've gotta big release I'm working on for the library just now so it would be nice to get it all working.

**Comment by Fatih90** [comment]
its almost 2017 and still not published

**Comment by JimBobSquarePants** [comment]
Ummm... Thanks for pointing that out. I guess a PR is out of the question?

**Comment by dampee** [comment]
There is already a package called responsive, so you need another name (in lower case). I suggest responsive-bp.  To publish a package check out this pretty [easy and short tutorial video](https://docs.npmjs.com/getting-started/publishing-npm-packages) of 2:41 explaining it all.  First **log in**, then just run `npm publish` from your Node command line.

I would have done it from my fork, but wanted to check it first here.  My npm username is dampee.

**Comment by dampee** [comment]
I was wondering how it works with bower.io. It's a link to your git repo, so you don't need to push anything?

**Comment by dampee** [comment]
Published on Responsive using my own masterbranch (including commits from pull request #96 and #97). 
If I receive the npm username from James, I'll add him as an owner. 

This issue can be closed: https://www.npmjs.com/package/responsive-bp/

**Comment by JimBobSquarePants** [comment]
Thanks for this @dampee So awesome of you to help!
