### ISSUE TITLE
Calling navigation('hide') can break scrolling

### ISSUE THREAD

**Issue by andiih** [ResponsiveBP/Responsive#76]
Calling .navgation('hide') on a closed menu (sometimes a few times) can break site scrolling.

To reproduce visit

http://plnkr.co/edit/gC1KAl9TYm84BH7m4jo2

Press play
Ensure your browser window is small enough that you see a scrollbar in the window on the right (or open that as a popup)

Click any of the large grey boxes  [which call $('nav').navgation('hide'); on click] until the scroll bar disappears.
Try to scroll.

**Comment by JimBobSquarePants** [comment]
I've got a fix for this in the works. (It's actually pretty simple) just struggling to get time to do an update at the mo.
