### ISSUE TITLE
Modal race condition

### ISSUE THREAD

**Issue by zyuhel** [ResponsiveBP/Responsive#77]
Sometimes if you hide and show modal window. Modal windows stops working until page restart.

Also if you run code to show modal while modal is shown, the modal window won't disappear.

**Comment by zyuhel** [comment]
It seems that issue is somewhere in Modal.prototype.overlay.

**Comment by JimBobSquarePants** [comment]
Thanks for raising this.

Could you perhaps supply some example code to demonstrate the issue? Also what version are you running?

**Comment by zyuhel** [comment]
I was using 4.1.0. Downloaded 4.1.1 issue still exists. Easiest way to duplicate is bind showing one modal on button in other modal window.

**Comment by JimBobSquarePants** [comment]
I'm really going to have to see a code example.

**Comment by zyuhel** [comment]
Yes of course. Look for example here - http://codepen.io/anon/pen/dYJZad 
It is example of calling modal within modal, after it modals won't work.

**Comment by JimBobSquarePants** [comment]
Thanks for that. Here's a working version containing nested modals. I'm using the data api to reduce the amount of core required.

http://codepen.io/anon/pen/PPEeQY

**Comment by zyuhel** [comment]
How could i repeat it using js? Or is it possible using only data api?
