### ISSUE TITLE
Documentation -> CSS -> Base -> Text Layout Helpers: Missing example for "{text-align}-{grid range}" and "{text-align}-{grid range}-only"

### ISSUE THREAD

**Issue by dirkeinecke** [ResponsiveBP/Responsive#81]
Documentation -> CSS -> Base -> Text Layout Helpers:
(http://responsivebp.com/css/base/#texthelpers)

Missing example for "`{text-align}-{grid range}`" and "`{text-align}-{grid range}-only`"

So nobody knows how to use this feature.

**Comment by JimBobSquarePants** [comment]
Would you consider sending a pull request? I've got a link on each page entitled "Edit page on Github" which links to the respective file in the gh_pages branch.

>So nobody knows how to use this feature.

I think that's a little strong. You're the first person to bring this up. The syntax follows the same structure as the layout helpers  so I would have thought that would have been indicative to their functionality.

**Comment by dirkeinecke** [comment]
General structure in the documentation:
`{text-align}-{grid range}-only`

Classes in the CSS file:

`.text-xxs-push-only` -> exists
`.text-xs-push-only` -> missing
`.text-s-push-only` -> missing
`.text-m-push-only` -> missing
`.text-l-push-only` -> missing

`.text-xxs-push-only` -> exists
`.text-xs-push-only` -> missing
`.text-s-push-only` -> missing
`.text-m-push-only` -> missing
`.text-l-push-only` -> missing

Example for general structure to real word values:

`{text-align}-{grid range}-only`
`text-push-xxs-only`

... but this does not match with the existing class `text-xxs-push-only` in the css file.

What is wrong? CSS file or documentation?

**Comment by JimBobSquarePants** [comment]
Looks to me like you've uncovered a bug.

https://github.com/ResponsiveBP/Responsive/blob/master/src/sass/utilities/mixins/_text-align.scss#L74

The instructions there should all have the `-only` suffix. I'll get it updated asap.
