### ISSUE TITLE
Just using the grid scss

### ISSUE THREAD

**Issue by welcomebrand** [ResponsiveBP/Responsive#84]
Not broken or anything but is there a good way to just use the grid from this framework? I don't need all the other stuff around it but there are lots of variables in the grid file that will mean I need to start going through and including other files to make sure it works so wondered if there's a quick guide on what to include just to get grids working?

**Comment by JimBobSquarePants** [comment]
You should only need the variables, normalize, grid, and the breakpoints mixin. 

I do however strongly recommend using it as a whole. It's very small and you will be surprised just at how many browser quirks I've ironed out. Take a look at forms.scss for example.
