### ISSUE TITLE
data-table-list issue

### ISSUE THREAD

**Issue by craigs100** [ResponsiveBP/Responsive#86]
I just added the attribute data-table-list as shown in the docs to a table within an MCE RTE (Umbraco 7.3.6 site). When the page is saved, instead of the table tag being `<table data-table-list class="someclass">` as shown in the ResponsiveBP example. it becomes `<table data-table-list="" class="someclass">` and doesn't seem to do anything. Is there a solution for this?

Thanks,

Craig

**Comment by JimBobSquarePants** [comment]
Hi Craig,

Could you please supply a little more detail than "it doesn't seem to do anything" so I can debug? 

- Do you mean in the front end? 
- Are there any errors in the developer tools console?
- Is everything correctly referenced?
- What version of Responsive you are using?

Thanks

James

**Comment by craigs100** [comment]
Sorry James, the Solution is, it's Bootstrap, not Responsive. Working too hard on a Sunday. As you were :( Would delete the thread if I could.

**Comment by JimBobSquarePants** [comment]
Hehehe... No worries. Don't work too hard!
