### ISSUE TITLE
Feature Request: Execution Order of MediaQueries

### ISSUE THREAD

**Issue by craigs100** [ResponsiveBP/Responsive#87]
Have just switched over from a Bootstrap project to a private project I want to use ResponsiveBP in. I'm finding I'm having to write far more HTML with ResponsiveBP because it appears to require a discrete definition of col-xxx-xxx for each size of a section. So to have a column be 10 wide from xxs to up s then switch to 5 wide at m and above, I'm having to write "col-xxs10 col-xs-10 col-s-10 col-m-5 col-l-5" instead of simply "col-xxs10 col-m-5" which I think is more logical (thinking of mobile first) and certainly less bloat code-wise. Not to mention bandwidth and dev time. Could it be implemented or is it too hard/not in keeping with project aims?

**Comment by eoutvik** [comment]
"col-s-10 col-m-5" should be sufficient

**Comment by craigs100** [comment]
Thanks for that. I had some hidden-xx in there causing complications so it's the hidden-xx/visible-xx that I should have been talking about really. It would be cool if you could do the same i.e. "hidden-xxs visible-m", or "hidden-xxs col-m-5" (the col-m-5 negating the hidden).

**Comment by JimBobSquarePants** [comment]
Thanks @eoutvik for chipping in, you're correct about the grid.

`col-xxs-10 col-m-5` will be 10 columns wide from `xxs` where it will switch to 5 columns wide from `m` and continue that way.

@craigs100  If you use `visible-m` without the `hidden-xxs` then the div will be hidden until you reach the `m` breakpoint.

`hidden-{bp}` means show until you reach the breakpoint.
`visible-{bp}` means hide until you reach the breakpoint.

`col-{bp}-{size}` determines the width only which aligns with every other framework I can think of. It should never affect visibility.

I find Responsive to be far less verbose than Bootstrap so if you are having issues and need pointers please let me know.

**Comment by craigs100** [comment]
Hi James,

Thanks for your explanation. Fiddling about with this to show it at m 
and l:-

<div class="visible-m col-m-1">
     <img src="/images/icon-cutlery.png" class="push" width="25">
</div>

And typing out my thoughts on what I thought would be a shorthand 
improvement, I realised there was no way out and the method you have is 
actually the best way all round. So it remains:-

<div class="visible-m visible-l col-m-1">
     <img src="/images/icon-cutlery.png" class="push" width="25">
</div>

as it's shorter than:-

<div class="hidde-xxs hidden-xs hidden-s col-m-1">
     <img src="/images/icon-cutlery.png" class="push" width="25">
</div>

Cheers,

Craig

**Comment by JimBobSquarePants** [comment]
Hey @craigs100 

``` html
<div class="visible-m visible-l col-m-1">
     <img src="/images/icon-cutlery.png" class="push" width="25">
</div>
```

Yeah, that'd be the correct way. I might look into the future switch the media queries mode for visibility to `bp-min` mode rather than `bp` which would allow

``` html
<div class="visible-m col-m-1">
     <img src="/images/icon-cutlery.png" class="push" width="25">
</div>
```

to do what you wanted. By introducing `visible-{bp}-only` classes I would replicate the existing behavior and make it more in line with other selectors.  It's a major breaking change though, so I can't introduce it until I need to create a V5, which there doesn't seem to be a demand for just now.

I'll close this off now.
