### ISSUE TITLE
SVG Images are stretched to 100 % width

### ISSUE THREAD

**Issue by arknu** [ResponsiveBP/Responsive#88]
The default styling in Responsive BP contains this style targeting SVG images:
```
_::-ms-reveal, img[src*='.svg'] {
    width: 100%;
}
```
This makes all SVG images stretch to 100 % width by default. 
Why would I ever want that? And I certainly wouldn't want it by default. I always end up having to override this style when using Responsive BP.

**Comment by JimBobSquarePants** [comment]
Why?.. Because this is the only way to get SVG images to scale to their container on IE 8-10.

It's a well known solution that Bootstrap suggests on their documentation also. 

http://getbootstrap.com/css/#callout-images-ie-svg
