### ISSUE TITLE
Print CSS hangs IE11 when printing

### ISSUE THREAD

**Issue by arknu** [ResponsiveBP/Responsive#89]
The following css in Responsive causes IE11 to hang when printing or using print preview:

```
*, :before, :after, *:first-letter, *:first-line {
    box-shadow: none !important;
    text-shadow: none !important;
    background: transparent !important;
    color: #000 !important; 
}
```

Specifically, the `*:first-line` part of the selector causes the problem. Remove that, and everything is fine.

See this issue for a similar problem: https://github.com/google/material-design-lite/issues/4129

**Comment by JimBobSquarePants** [comment]
Thanks for this. Looks like HTML5 Boilerplate have go this covered. Will implement a fix.

https://github.com/h5bp/html5-boilerplate/pull/1799

https://github.com/h5bp/html5-boilerplate/commit/9c98cfaffb305bbcc9dd31f3be04ffa8506d0095
