### ISSUE TITLE
Modal jumps underlying page if scrolled

### ISSUE THREAD

**Issue by mattbrailsford** [ResponsiveBP/Responsive#93]
When you open a modal (In Chrome on Windows at least) if you are scrolled down the page, when the modal opens, the underlying page scrolls back to the top, then on modal close, scrolls back to the previous position.

I understand this is to prevent the background scrolling and thus loosing position while the dialog is open, but when you have a semitrasparent modal background, it looks odd that the page beneath jumps rather than just maintaining it's current position.

I think it would be a much better user experience and less confusing if the page behind could stay at it's current scrolled position.

**Comment by mattbrailsford** [comment]
A little poking around, and there seems to be something about chrome not liking html element to have a height of 100%. Content gets cut off.

**Comment by mattbrailsford** [comment]
For some reason, setting height:auto !important; on the html element seems to make it work in chrome. Not tested in other browsers though.

**Comment by JimBobSquarePants** [comment]
Yeah that would make sense... I just had a quick test with the live responsive site and disabling the `height:100%` property in `[data-locked]` selector appeared to give us the behaviour you want. I'm pretty sure it never used to disable scrolling doing that. 

I'll have to build and test on multiple browsers to be sure. If you have a chance could you please do so.

**Comment by JimBobSquarePants** [comment]
Fixed in v4.1.4 

https://github.com/ResponsiveBP/Responsive/releases/tag/4.1.4
