### ISSUE TITLE
Repeated lines on the docs

### ISSUE THREAD

**Issue by lsrdg** [ResponsiveBP/Responsive#95]
On the branch: gh-pages
Page: javascript/00-carousel

The [lines 23 and 23](https://github.com/ResponsiveBP/Responsive/blob/gh-pages/javascript/00-carousel.html#L24) seem to be unrelated to the previous paragraph:

>  The carousel comes in two modes: Slide and Fade, both animated via CSS3 transitions. On browsers that do not support transitions they simply change without special effects.
_Comes with a markup API that allows running the plugin without writing a single line of JavaScript. This is Responsive's first class API and should be your first consideration when using a plugin._ 

Actually, they first appeared [here](https://github.com/ResponsiveBP/Responsive/blob/gh-pages/javascript/index.html#L45) where they do make sense:

> All plugins come with a data-attribute driven, markup API that allows running the plugin without writing a single line of JavaScript.
This is Responsive's first class API and should be your first consideration when using the plugins.
This API works in a similar, yet enhanced way to Bootstraps Markup API.

Should they be removed, improved or am I just missing something? Just let me know if I should propose a PR.

**Comment by lsrdg** [comment]
Sorry, my bad. All pages inside javascript/ contain those lines, and probably that was the intention. 
Closing this issue. 
Once the Javascript's docs are translated to Portuguese, I'll open an issue over there in other to find a better way to translate it. Anyway, it shouldn't affect to official docs.
 My apologies.

**Comment by JimBobSquarePants** [comment]
Sorry, I didn't get back to you sooner, I completely missed this. Yeah the sentences are completely intentional. I really want the dev to use the data-api

**Comment by lsrdg** [comment]
No worries and sorry, I should have checked that before creating the issue. It won't happen again. 
And that's totally understandable why should the data-api be used, thanks for reinforcing it. (:

**Comment by JimBobSquarePants** [comment]
Don't worry about it at all! 😄
