### ISSUE TITLE
the latest release doesn't open up in Mac

### ISSUE THREAD

**Issue by FernandoBoza** [ResponsiveBP/Responsive#99]
Tried to download from website, had to download from the 'release source' and from there even the dist 'responsive' file is still unable to open..  [img of the mac err](http://imgur.com/a/0BbCY)

Mac OS Sierra 2016
v 10.12.4 = Macbook Pro

**Comment by JimBobSquarePants** [comment]
It must be something to do with gulp-zip or the underlying code.
https://github.com/sindresorhus/gulp-zip/issues/79

**Comment by JimBobSquarePants** [comment]
I've updated the binary manually for now. Will look to fix the automated release asap

**Comment by JimBobSquarePants** [comment]
Not using gulp for v5. Closing.
